# -*- coding: utf-8 -*-
"""
Dicts and lists used in Cronometer json files
For salt, multiply by grams by 400 and add is as mg sodium.
"""
nutrients = {
    "Protein": [203, "g"],
    "Fat": [204, "g"],
    "Carbs": [205, "g"],
    "Ash": [207, "g"],
    "Energy": [208, "kcal"],
    "Starch": [209, "g"],
    "Sucrose": [210, "g"],
    "Glucose": [211, "g"],
    "Fructose": [212, "g"],
    "Lactose": [213, "g"],
    "Maltose": [214, "g"],
    "Alcohol": [221, "g"],
    "Water": [255, "g"],
    "Caffeine": [262, "mg"],
    "Theobromine": [263, "mg"],
    "Sugars": [269, "g"],
    "Galactose": [287, "g"],
    "Fiber": [291, "g"],
    "Calcium": [301, "mg"],
    "Iron": [303, "mg"],
    "Magnesium": [304, "mg"],
    "Phosphorus": [305, "mg"],
    "Potassium": [306, "mg"],
    "Sodium": [307, "mg"],
    "Zinc": [309, "mg"],
    "Copper": [312, "mg"],
    "Fluoride": [313, "ug"],
    "Manganese": [315, "mg"],
    "Selenium": [317, "ug"],
    "Vitamin A": [318, "IU"],
    "Retinol": [319, "ug"],
    "Retinol Activity Equivalent": [320, "ug"],
    "Beta-carotene": [321, "ug"],
    "Alpha-carotene": [322, "ug"],
    "Vitamin E": [323, "mg"],
    "Vitamin D": [324, "IU"],
    "Vitamin D2 (ergocalciferol)": [325, "ug"],
    "Vitamin D3 (cholecalciferol)": [326, "ug"],
    "Vitamin D (D2 + D3)": [328, "ug"],
    "Beta-cryptoxanthin": [334, "ug"],
    "Lycopene": [337, "ug"],
    "Lutein+Zeaxanthin": [338, "ug"],
    "Beta Tocopherol": [341, "mg"],
    "Gamma Tocopherol": [342, "mg"],
    "Delta Tocopherol": [343, "mg"],
    "Vitamin C": [401, "mg"],
    "B1 (Thiamine)": [404, "mg"],
    "B2 (Riboflavin)": [405, "mg"],
    "B3 (Niacin)": [406, "mg"],
    "B5 (Pantothenic Acid)": [410, "mg"],
    "B6 (Pyridoxine)": [415, "mg"],
    "Folate": [417, "ug"],
    "B12 (Cobalamin)": [418, "ug"],
    "Choline": [421, "mg"],
    "Vitamin K": [430, "ug"],
    "Folic acid": [431, "ug"],
    "Betaine": [454, "mg"],
    "Tryptophan": [501, "g"],
    "Threonine": [502, "g"],
    "Isoleucine": [503, "g"],
    "Leucine": [504, "g"],
    "Lysine": [505, "g"],
    "Methionine": [506, "g"],
    "Cystine": [507, "g"],
    "Phenylalanine": [508, "g"],
    "Tyrosine": [509, "g"],
    "Valine": [510, "g"],
    "Arginine": [511, "g"],
    "Histidine": [512, "g"],
    "Alanine": [513, "g"],
    "Aspartic acid": [514, "g"],
    "Glutamic acid": [515, "g"],
    "Glycine": [516, "g"],
    "Proline": [517, "g"],
    "Serine": [518, "g"],
    "Hydroxyproline": [521, "g"],
    "Cholesterol": [601, "mg"],
    "Trans-Fats": [605, "g"],
    "Saturated Fat": [606, "g"],
    "Phytosterol": [636, "mg"],
    "Stigmasterol": [638, "mg"],
    "Campesterol": [639, "mg"],
    "Beta-sitosterol": [641, "mg"],
    "Monounsaturated Fat": [645, "g"],
    "Polyunsaturated Fat": [646, "g"],
    "Omega-3": [10001, "g"],
    "Omega-6": [10002, "g"],
    "Chromium": [10003, "ug"],
    "Biotin": [10004, "ug"],
    "Iodine": [10005, "mg"],
    "Sugar Alcohol": [10007, "g"],
    "Molybdenum": [10008, "ug"],
    "Added Sugars": [10009, "g"],
    "Allulose": [10010, "g"],
    "Beta-Hydroxybutyrate": [10011, "g"],
    "Oxalate": [10012, "mg"],
}

category = {
    "": 0,
    "Baby Foods": 1,
    "Baked Products": 2,
    "Beef Products": 3,
    "Beverages": 4,
    "Breakfast Cereals": 5,
    "Cereal Grains and Pasta": 6,
    "Dairy and Egg Products": 7,
    "Ethnic Foods": 8,
    "Fast Foods": 9,
    "Fats and Oils": 10,
    "Finfish and Shellfish Products": 11,
    "Fruits and Fruit Juices": 12,
    "Lamb, Veal, and Game Products": 13,
    "Legumes and Legume Products": 14,
    "Meals, Entrees, and Sidedishes": 15,
    "Nut and Seed Products": 16,
    "Pork Products": 17,
    "Poultry Products": 18,
    "Restaurant Foods": 19,
    "Sausages and Luncheon Meats": 20,
    "Snacks": 21,
    "Soups, Sauces, and Gravies": 22,
    "Spices and Herbs": 23,
    "Supplements": 24,
    "Sweets": 25,
    "Vegetables and Vegetable Products": 26,
}

tags = [
    "Whole",
    "Brand",
    "Restaurant",
    "Supplement",
    "Seafood",
    "Vegetarian",
    "Vegan",
    "Dairy",
    "Nuts",
]

labels = {
    "American Label": "AMERICAN",
    "American 2016": "AMERICAN_2016",
    "European Label": "EU",
    "Australia/NZ Label": "AUSTRALIA_NZ",
    "Canadian Label": "CANADIAN",
}

languages = {
    "en": 20829061,
    "fr": 20829062,
    "es": 20829063,
    "de": 20829064,
    "it": 20829065,
    "pl": 20829066,
}
